package com.example.razorpay.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO sent by the frontend after a successful Razorpay payment.
 * Used by the backend to verify the payment signature.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentVerificationRequest {

    /** Razorpay Payment ID returned by checkout (prefix: pay_) */
    private String razorpayPaymentId;

    /** Razorpay Order ID (prefix: order_) */
    private String razorpayOrderId;

    /** HMAC-SHA256 signature generated by Razorpay */
    private String razorpaySignature;
}
